FROM apache/airflow:2.9.3-python3.12

USER root

RUN apt-get update && apt-get install -y \
    openjdk-17-jdk \
    wget \
    curl \
    git \
    unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

USER airflow

RUN pip install --no-cache-dir \
    "apache-airflow-providers-apache-spark==5.0.0" \
    "pyspark==3.5.1" \
    "pandas==2.2.2" \
    "pyarrow==16.1.0" \
    "cassandra-driver==3.29.2" \
    "kafka-python==2.0.2" \
    "elasticsearch==8.13.2"